### ISSUE TITLE
fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [khibino/haskell-json-rpc-generic#2]
```
json-rpc-generic               > /tmp/stack-f7d350cae3262115/json-rpc-generic-0.2.1.6/src/Data/JsonRpc/Generic.hs:100:44: error:
json-rpc-generic               >     • Couldn't match type: Data.Aeson.KeyMap.KeyMap Value
json-rpc-generic               >                      with: HashMap.HashMap T.Text v0
json-rpc-generic               >       Expected: HashMap.HashMap T.Text v0
json-rpc-generic               >         Actual: aeson-2.0.2.0:Data.Aeson.Types.Internal.Object
json-rpc-generic               >     • In the first argument of ‘HashMap.keys’, namely ‘m’
json-rpc-generic               >       In the first argument of ‘Set.fromList’, namely ‘(HashMap.keys m)’
json-rpc-generic               >       In the first argument of ‘(\\)’, namely
json-rpc-generic               >         ‘Set.fromList (HashMap.keys m)’
json-rpc-generic               >     |
json-rpc-generic               > 100 |         inv  =  Set.fromList (HashMap.keys m) \\
json-rpc-generic               >     |                                            ^
```
